# Generated by Django 5.2.7 on 2025-11-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='area',
            field=models.CharField(blank=True, null=True, verbose_name='Area'),
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='completed_date',
            field=models.CharField(blank=True, null=True, verbose_name='Completed date'),
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='location',
            field=models.TextField(blank=True, null=True, verbose_name='Location'),
        ),
    ]
