# Generated by Django 5.2.7 on 2025-11-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_area_projecttranslation_completed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttranslation',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Location'),
        ),
    ]
