# Generated by Django 5.2.7 on 2025-12-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_image_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='rank',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Rank'),
        ),
    ]
