# Generated by Django 5.2.7 on 2025-12-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_rank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('rank',)},
        ),
    ]
