# Generated by Django 5.2.7 on 2025-12-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('requested_url', models.URLField()),
                ('user_agent', models.TextField()),
                ('operating_system', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.CharField(choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('bot', 'Bot'), ('', 'Not applied')], default='', max_length=10)),
                ('is_authenticated', models.BooleanField(default=False)),
            ],
        ),
    ]
