# Generated by Django 6.0 on 2025-12-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='requested_url_origin',
            field=models.TextField(blank=True),
        ),
    ]
